# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'administrator_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdministratorDialog(object):
    def setupUi(self, AdministratorDialog):
        AdministratorDialog.setObjectName("AdministratorDialog")
        AdministratorDialog.resize(362, 365)
        self.gridLayout_2 = QtWidgets.QGridLayout(AdministratorDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Title = QtWidgets.QLabel(AdministratorDialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.verticalLayout.addWidget(self.label_Title)
        self.label_Borrower = QtWidgets.QLabel(AdministratorDialog)
        self.label_Borrower.setObjectName("label_Borrower")
        self.verticalLayout.addWidget(self.label_Borrower)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_Borrower = QtWidgets.QLineEdit(AdministratorDialog)
        self.lineEdit_Borrower.setObjectName("lineEdit_Borrower")
        self.horizontalLayout.addWidget(self.lineEdit_Borrower)
        self.pushButton_AddBorrower = QtWidgets.QPushButton(AdministratorDialog)
        self.pushButton_AddBorrower.setAutoDefault(False)
        self.pushButton_AddBorrower.setObjectName("pushButton_AddBorrower")
        self.horizontalLayout.addWidget(self.pushButton_AddBorrower)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_Borrower = QtWidgets.QComboBox(AdministratorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Borrower.sizePolicy().hasHeightForWidth())
        self.comboBox_Borrower.setSizePolicy(sizePolicy)
        self.comboBox_Borrower.setObjectName("comboBox_Borrower")
        self.horizontalLayout_2.addWidget(self.comboBox_Borrower)
        self.pushButton_RemoveBorrower = QtWidgets.QPushButton(AdministratorDialog)
        self.pushButton_RemoveBorrower.setAutoDefault(False)
        self.pushButton_RemoveBorrower.setObjectName("pushButton_RemoveBorrower")
        self.horizontalLayout_2.addWidget(self.pushButton_RemoveBorrower)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_Asset = QtWidgets.QLabel(AdministratorDialog)
        self.label_Asset.setObjectName("label_Asset")
        self.verticalLayout.addWidget(self.label_Asset)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_Asset = QtWidgets.QLineEdit(AdministratorDialog)
        self.lineEdit_Asset.setObjectName("lineEdit_Asset")
        self.horizontalLayout_5.addWidget(self.lineEdit_Asset)
        self.spinBox_AddAsset = QtWidgets.QSpinBox(AdministratorDialog)
        self.spinBox_AddAsset.setMaximum(9999)
        self.spinBox_AddAsset.setObjectName("spinBox_AddAsset")
        self.horizontalLayout_5.addWidget(self.spinBox_AddAsset)
        self.pushButton_AddAsset = QtWidgets.QPushButton(AdministratorDialog)
        self.pushButton_AddAsset.setAutoDefault(False)
        self.pushButton_AddAsset.setObjectName("pushButton_AddAsset")
        self.horizontalLayout_5.addWidget(self.pushButton_AddAsset)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_Asset = QtWidgets.QComboBox(AdministratorDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Asset.sizePolicy().hasHeightForWidth())
        self.comboBox_Asset.setSizePolicy(sizePolicy)
        self.comboBox_Asset.setObjectName("comboBox_Asset")
        self.horizontalLayout_7.addWidget(self.comboBox_Asset)
        self.spinBox_RemoveAsset = QtWidgets.QSpinBox(AdministratorDialog)
        self.spinBox_RemoveAsset.setMaximum(9999)
        self.spinBox_RemoveAsset.setObjectName("spinBox_RemoveAsset")
        self.horizontalLayout_7.addWidget(self.spinBox_RemoveAsset)
        self.pushButton_RemoveAsset = QtWidgets.QPushButton(AdministratorDialog)
        self.pushButton_RemoveAsset.setAutoDefault(False)
        self.pushButton_RemoveAsset.setObjectName("pushButton_RemoveAsset")
        self.horizontalLayout_7.addWidget(self.pushButton_RemoveAsset)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AdministratorDialog)
        self.pushButton_Close = QtWidgets.QPushButton()
        self.pushButton_Close.setAutoDefault(False)
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.buttonBox.addButton(self.pushButton_Close, QtWidgets.QDialogButtonBox.RejectRole)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(AdministratorDialog)
        QtCore.QMetaObject.connectSlotsByName(AdministratorDialog)

    def retranslateUi(self, AdministratorDialog):
        _translate = QtCore.QCoreApplication.translate
        AdministratorDialog.setWindowTitle(_translate("AdministratorDialog", "Administrator"))
        self.label_Title.setText(_translate("AdministratorDialog", "Administrator"))
        self.label_Borrower.setText(_translate("AdministratorDialog", "Borrower"))
        self.pushButton_AddBorrower.setText(_translate("AdministratorDialog", "Add"))
        self.pushButton_RemoveBorrower.setText(_translate("AdministratorDialog", "Remove"))
        self.label_Asset.setText(_translate("AdministratorDialog", "Equipment"))
        self.pushButton_AddAsset.setText(_translate("AdministratorDialog", "Add"))
        self.pushButton_RemoveAsset.setText(_translate("AdministratorDialog", "Remove"))
        self.pushButton_Close.setText(_translate("AdministratorDialog", "Close"))
