# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'borrow_list_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BorrowListDialog(object):
    def setupUi(self, BorrowListDialog):
        BorrowListDialog.setObjectName("BorrowListDialog")
        BorrowListDialog.resize(565, 475)
        self.gridLayout = QtWidgets.QGridLayout(BorrowListDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Title = QtWidgets.QLabel(BorrowListDialog)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_Title.setFont(font)
        self.label_Title.setObjectName("label_Title")
        self.verticalLayout.addWidget(self.label_Title)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_Borrower = QtWidgets.QLabel(BorrowListDialog)
        self.label_Borrower.setObjectName("label_Borrower")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Borrower)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comboBox_Borrower = QtWidgets.QComboBox(BorrowListDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Borrower.sizePolicy().hasHeightForWidth())
        self.comboBox_Borrower.setSizePolicy(sizePolicy)
        self.comboBox_Borrower.setObjectName("comboBox_Borrower")
        self.horizontalLayout_6.addWidget(self.comboBox_Borrower)
        self.pushButton_ClearBorrower = QtWidgets.QPushButton(BorrowListDialog)
        self.pushButton_ClearBorrower.setAutoDefault(False)
        self.pushButton_ClearBorrower.setObjectName("pushButton_ClearBorrower")
        self.horizontalLayout_6.addWidget(self.pushButton_ClearBorrower)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_Asset = QtWidgets.QLabel(BorrowListDialog)
        self.label_Asset.setObjectName("label_Asset")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Asset)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comboBox_Asset = QtWidgets.QComboBox(BorrowListDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_Asset.sizePolicy().hasHeightForWidth())
        self.comboBox_Asset.setSizePolicy(sizePolicy)
        self.comboBox_Asset.setObjectName("comboBox_Asset")
        self.horizontalLayout_7.addWidget(self.comboBox_Asset)
        self.pushButton_ClearAsset = QtWidgets.QPushButton(BorrowListDialog)
        self.pushButton_ClearAsset.setAutoDefault(False)
        self.pushButton_ClearAsset.setObjectName("pushButton_ClearAsset")
        self.horizontalLayout_7.addWidget(self.pushButton_ClearAsset)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_All = QtWidgets.QRadioButton(BorrowListDialog)
        self.radioButton_All.setChecked(True)
        self.radioButton_All.setObjectName("radioButton_All")
        self.horizontalLayout_5.addWidget(self.radioButton_All)
        self.radioButton_Borrowing = QtWidgets.QRadioButton(BorrowListDialog)
        self.radioButton_Borrowing.setObjectName("radioButton_Borrowing")
        self.horizontalLayout_5.addWidget(self.radioButton_Borrowing)
        self.radioButton_Overdue = QtWidgets.QRadioButton(BorrowListDialog)
        self.radioButton_Overdue.setObjectName("radioButton_Overdue")
        self.horizontalLayout_5.addWidget(self.radioButton_Overdue)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtWidgets.QTableWidget(BorrowListDialog)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        header = self.tableWidget.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(BorrowListDialog)
        self.pushButton_Close = QtWidgets.QPushButton()
        self.pushButton_Close.setAutoDefault(False)
        self.pushButton_Close.setObjectName("pushButton_Close")
        self.buttonBox.addButton(self.pushButton_Close, QtWidgets.QDialogButtonBox.RejectRole)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(BorrowListDialog)
        QtCore.QMetaObject.connectSlotsByName(BorrowListDialog)

    def retranslateUi(self, BorrowListDialog):
        _translate = QtCore.QCoreApplication.translate
        BorrowListDialog.setWindowTitle(_translate("BorrowListDialog", "Borrow List"))
        self.label_Title.setText(_translate("BorrowListDialog", "Borrow List"))
        self.label_Borrower.setText(_translate("BorrowListDialog", "Borrower: "))
        self.pushButton_ClearBorrower.setText(_translate("BorrowListDialog", "Clear"))
        self.label_Asset.setText(_translate("BorrowListDialog", "Equipment: "))
        self.pushButton_ClearAsset.setText(_translate("BorrowListDialog", "Clear"))
        self.radioButton_All.setText(_translate("BorrowListDialog", "All"))
        self.radioButton_Borrowing.setText(_translate("BorrowListDialog", "Borrowing"))
        self.radioButton_Overdue.setText(_translate("BorrowListDialog", "Overdue"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("BorrowListDialog", "Borrower"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("BorrowListDialog", "Equipment"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("BorrowListDialog", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("BorrowListDialog", "Date Due"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("BorrowListDialog", "Is Returned"))
        self.pushButton_Close.setText(_translate("AdministratorDialog", "Close"))
